// <auto-generated />
using System;
using INTEXII.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INTEXII.Migrations.IntexW24dataset
{
    [DbContext(typeof(IntexW24datasetContext))]
    partial class IntexW24datasetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("INTEXII.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_ID");

                    b.Property<double?>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<string>("CountryOfResidence")
                        .HasColumnType("TEXT")
                        .HasColumnName("country_of_residence");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("CustomerId");

                    b.HasIndex(new[] { "CustomerId" }, "IX_Customers_customer_ID")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("INTEXII.Models.LineItem", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_ID");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_ID");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qty");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rating");

                    b.HasKey("TransactionId", "ProductId");

                    b.ToTable("LineItems");
                });

            modelBuilder.Entity("INTEXII.Models.Order", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_ID");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bank");

                    b.Property<string>("CountryOfTransaction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("country_of_transaction");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_ID");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("day_of_week");

                    b.Property<string>("EntryMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_mode");

                    b.Property<int>("Fraud")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fraud");

                    b.Property<int>("PredFraud")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pred_fraud");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shipping_address");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time");

                    b.Property<string>("TypeOfCard")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type_of_card");

                    b.Property<string>("TypeOfTransaction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type_of_transaction");

                    b.HasKey("TransactionId");

                    b.HasIndex(new[] { "TransactionId" }, "IX_Orders_transaction_ID")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("INTEXII.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_ID");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ImgLink")
                        .HasColumnType("TEXT")
                        .HasColumnName("img_link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("NumParts")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("num_parts");

                    b.Property<double?>("PopularityRank")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("popularity_rank");

                    b.Property<int>("Price")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("price");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("TEXT")
                        .HasColumnName("primary_color");

                    b.Property<string>("PublicCategory")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Recommendation1")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("recommendation1");

                    b.Property<int?>("Recommendation2")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("recommendation2");

                    b.Property<int?>("Recommendation3")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("recommendation3");

                    b.Property<int?>("Recommendation4")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("recommendation4");

                    b.Property<int?>("Recommendation5")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("recommendation5");

                    b.Property<string>("SecondaryColor")
                        .HasColumnType("TEXT")
                        .HasColumnName("secondary_color");

                    b.Property<double?>("Similarity1")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("similarity1");

                    b.Property<double?>("Similarity2")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("similarity2");

                    b.Property<double?>("Similarity3")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("similarity3");

                    b.Property<double?>("Similarity4")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("similarity4");

                    b.Property<double?>("Similarity5")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("similarity5");

                    b.Property<int>("Year")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("year");

                    b.HasKey("ProductId");

                    b.HasIndex(new[] { "ProductId" }, "IX_Products_product_ID")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("INTEXII.Models.Recommendation", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_id");

                    b.Property<int>("RecProdId1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rec_prod_id_1");

                    b.Property<int>("RecProdId2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rec_prod_id_2");

                    b.Property<int>("RecProdId3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rec_prod_id_3");

                    b.Property<int>("RecProdId4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rec_prod_id_4");

                    b.HasKey("CustomerId");

                    b.ToTable("Recommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
